Update copyright in FLUID "about" window.
Update fltk-config to support all C++ file extensions.

Make background of FLTK logo transparent.

Disable overlays if the scheme is set.

Fix table cell formatting in Fl_Help_View.  Still need to resolve an
issue with column widths vs. table widths.


git-svn-id: file:///fltk/svn/fltk/branches/branch-1.1@1965 ea41ed52-d2ee-0310-a9c1-e6b18d33e121

diff --git a/fltk-config.in b/fltk-config.in
--- a/fltk-config.in
+++ b/fltk-config.in
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# "$Id: fltk-config.in,v 1.12.2.7 2002/01/01 15:11:27 easysw Exp $"
+# "$Id: fltk-config.in,v 1.12.2.8 2002/02/20 13:02:25 easysw Exp $"
 # 
 # FLTK configuration utility.
 #
@@ -200,7 +200,25 @@ if test -n "$echo_help"; then usage 1
 fi
 
 if test -n "$compile"; then
-    prog=`basename $compile .cxx`
+    case $compile in
+        *.cxx)
+            prog=`basename $compile .cxx`
+	    ;;
+        *.cpp)
+            prog=`basename $compile .cpp`
+	    ;;
+        *.cc)
+            prog=`basename $compile .cc`
+	    ;;
+        *.C)
+            prog=`basename $compile .C`
+	    ;;
+	*)
+	    echo "ERROR: Unknown/bad C++ source file extension on \"$compile\"!"
+	    exit 1
+	    ;;
+    esac
+	    
     post=$prog
 
     echo $CXX $CXXFLAGS -o $prog $compile $LDSTATIC
